### PR TITLE
Fix timezone offset & 新創營結束 Stable version

### PR DESCRIPTION
**Pull request by jackyhuang85**

### CODE REVIEW

**Comment by jackyhuang85** [comment]
把 env 變數都存在 .env 裡，不 push 上來

**Comment by jwwandy** [comment]
Could we have a sample .env file where all env var needs are listed, but not assigned

**Comment by jackyhuang85** [comment]
@jwwandy 
> ..where all env var needs are listed..

你是指所有專案的 env 全部放在一個 file 裡？

**Comment by jwwandy** [comment]
Something like a *.env file with
```bash
ENV1=
ENV2=
ENV3=
```

**Comment by jackyhuang85** [comment]
i knew it, and done that.
that's just a claim

yet, another question is 
where should we put those env files? local?

**Comment by jackyhuang85** [comment]
@jwwandy 補上 env
另外要把 README 補完

**Review by jwwandy — APPROVED** [review]

**Pull request merged**
